title: "Configuration Microsoft Purview 2026 - nLPD Suisse"
description: "Documentation technique complète pour PME suisses : DLP, classification et conformité nLPD."
url: "https://doit4everyone.github.io"
baseurl: "/microsoft-purview-configuration-2026-nLPD"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
